sudo: required
language: node_js
services:
  - docker
node_js:
  - v12
  - v10
  - v8
## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  # use the new "ci" command for fastest installs on CI
  - npm ci

before_script:
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - docker run -d -p 27017:27017 mongo:4.0
  - docker ps -a
  - npm start -- --silent &
env:
  - MONGODB_URI=mongodb://localhost/connect-mongo-test
script:
  - npm run test
