sudo: true
language: node_js
node_js:
  - 12
services:
  - docker
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'    
script:
  - npm run test
